const express = require('express');
const router = express.Router();

router.get('/linux-commands', (req, res) => {
    const linuxCommands = [
        { command: 'ls', description: 'Lists a directory’s content', example: 'ls' },
        { command: 'pwd', description: 'Shows the current working directory’s path', example: 'pwd' },
        { command: 'cd', description: 'Changes the working directory', example: 'cd directory_name' },
        { command: 'mkdir', description: 'Creates a new directory', example: 'mkdir new_directory' },
        { command: 'rm', description: 'Deletes a file', example: 'rm file.txt' },
        { command: 'cp', description: 'Copies files and directories, including their content', example: 'cp source destination' },
        { command: 'mv', description: 'Moves or renames files and directories', example: 'mv old_filename new_filename' },
        { command: 'touch', description: 'Creates a new empty file', example: 'touch new_file.txt' },
        { command: 'file', description: 'Checks a file’s type', example: 'file filename' },
        { command: 'zip', description: 'Creates a ZIP archive', example: 'zip archive.zip file1 file2' },
        { command: 'unzip', description: 'Extracts files from a ZIP archive', example: 'unzip archive.zip' },
        { command: 'tar', description: 'Archives files without compression in a TAR format', example: 'tar -cvf archive.tar file1 file2' },
        { command: 'nano', description: 'Edits a file with the nano text editor', example: 'nano filename' },
        { command: 'vi', description: 'Edits a file with the vi text editor', example: 'vi filename' },
        { command: 'jed', description: 'Edits a file with the jed text editor', example: 'jed filename' },
        { command: 'cat', description: 'Lists, combines, and writes a file’s content as standard output', example: 'cat filename' },
        { command: 'grep', description: 'Searches a string within a file', example: 'grep pattern filename' },
        { command: 'sed', description: 'Finds, replaces, or deletes patterns in a file', example: 'sed s/old/new/g filename' },
        { command: 'head', description: 'Displays a file’s first ten lines', example: 'head filename' },
        { command: 'tail', description: 'Prints a file’s last ten lines', example: 'tail filename' },
        { command: 'awk', description: 'Finds and manipulates patterns in a file', example: 'awk pattern filename' },
        { command: 'sort', description: 'Reorders a file’s content', example: 'sort filename' },
        { command: 'cut', description: 'Sections and prints lines from a file', example: 'cut -f1 filename' },
        { command: 'diff', description: 'Compares two files’ content and their differences', example: 'diff file1 file2' },
        { command: 'tee', description: 'Prints command outputs in Terminal and a file', example: 'command | tee output.txt' },
        { command: 'locate', description: 'Finds files in a system’s database', example: 'locate filename' },
        { command: 'find', description: 'Outputs a file or folder’s location', example: 'find /path/to/search -name "filename"' },
        { command: 'sudo', description: 'Runs a command as a superuser', example: 'sudo command' },
        { command: 'su', description: 'Runs programs in the current shell as another user', example: 'su username' },
        { command: 'chmod', description: 'Modifies a file’s read, write, and execute permissions', example: 'chmod 755 filename' },
        { command: 'chown', description: 'Changes a file, directory, or symbolic link’s ownership', example: 'chown user:group filename' },
        { command: 'useradd', description: 'Creates a new user account', example: 'useradd username' },
        { command: 'userdel', description: 'Removes a user account', example: 'userdel username' },
        { command: 'df', description: 'Displays the system’s overall disk space usage', example: 'df -h' },
        { command: 'du', description: 'Checks a file or directory’s storage consumption', example: 'du -h filename' },
        { command: 'top', description: 'Displays running processes and the system’s resource usage', example: 'top' },
        { command: 'htop', description: 'Works like top but with an interactive user interface', example: 'htop' },
        { command: 'ps', description: 'Creates a snapshot of all running processes', example: 'ps aux' },
        { command: 'uname', description: 'Prints information about your machine’s kernel, name, and hardware', example: 'uname -a' },
        { command: 'hostname', description: 'Shows your system’s hostname', example: 'hostname' },
        { command: 'time', description: 'Calculates commands’ execution time', example: 'time command' },
        { command: 'systemctl', description: 'Manages system services', example: 'systemctl status service_name' },
        { command: 'watch', description: 'Runs another command continuously', example: 'watch command' },
        { command: 'jobs', description: 'Displays a shell’s running processes with their statuses', example: 'jobs' },
        { command: 'kill', description: 'Terminates a running process', example: 'kill process_id' },
        { command: 'shutdown', description: 'Turns off or restarts the system', example: 'shutdown now' },
        { command: 'ping', description: 'Checks the system’s network connectivity', example: 'ping google.com' },
        { command: 'wget', description: 'Downloads files from a URL', example: 'wget https://example.com/file' },
        { command: 'curl', description: 'Transmits data between servers using URLs', example: 'curl -O https://example.com/file' },
        { command: 'scp', description: 'Securely copies files or directories to another system', example: 'scp file.txt user@remote:/path' },
        { command: 'rsync', description: 'Synchronizes content between directories or machines', example: 'rsync -av source/ destination/' },
        { command: 'lfconfig', description: 'Displays the system’s network interfaces and their configurations', example: 'ifconfig' },
        { command: 'netstat', description: 'Shows the system’s network information, like routing and sockets', example: 'netstat -an' },
        { command: 'traceroute', description: 'Tracks a packet’s hops to its destination', example: 'traceroute example.com' },
        { command: 'nslookup', description: 'Queries a domain’s IP address and vice versa', example: 'nslookup example.com' },
        { command: 'dig', description: 'Displays DNS information, including record types', example: 'dig example.com' },
        { command: 'history', description: 'Lists previously run commands', example: 'history' },
        { command: 'man', description: 'Shows a command’s manual', example: 'man command' },
        { command: 'echo', description: 'Prints a message as standard output', example: 'echo "Hello, World!"' },
        { command: 'ln', description: 'Links files or directories', example: 'ln -s source target' },
        { command: 'alias', description: 'Sets an alias for a command', example: 'alias ll="ls -l"' },
        { command: 'unalias', description: 'Removes an alias for a command', example: 'unalias ll' },
        { command: 'cal', description: 'Displays a calendar in Terminal', example: 'cal' },
        { command: 'apt-get', description: 'Manages Debian-based distros package libraries', example: 'apt-get install package_name' },
    ];

    res.json(linuxCommands);
});

module.exports = router;
