const express = require('express');
const router = express.Router();

router.get('/windows-commands', (req, res) => {
    const windowsCommands = [
        { command: 'AccessChk', description: 'Get the security descriptor (SDDL) for an object (file, directory, reg key).', example: 'AccessChk' },
        { command: 'ADDUSERS', description: 'Add or list users to/from a CSV file.', example: 'ADDUSERS' },
        { command: 'ADmodcmd', description: 'Active Directory Bulk Modify.', example: 'ADmodcmd' },
        { command: 'ARP', description: 'Address Resolution Protocol.', example: 'ARP' },
        { command: 'ASSOC', description: 'Change file extension associations.', example: 'ASSOC' },
        { command: 'ATTRIB', description: 'Change file attributes.', example: 'ATTRIB' },
        { command: 'BCDBOOT', description: 'Create or repair a system partition.', example: 'BCDBOOT' },
        { command: 'BCDEDIT', description: 'Manage Boot Configuration Data.', example: 'BCDEDIT' },
        { command: 'BITSADMIN', description: 'Background Intelligent Transfer Service.', example: 'BITSADMIN' },
        { command: 'BOOTREC', description: 'Repair or replace a partition boot sector.', example: 'BOOTREC' },
        { command: 'BREAK', description: 'Do nothing, successfully.', example: 'BREAK' },
        { command: 'BROWSTAT', description: 'Get domain, browser and PDC info.', example: 'BROWSTAT' },
        { command: 'CACLS', description: 'Change file permissions.', example: 'CACLS' },
        { command: 'CALL', description: 'Call one batch program from another.', example: 'CALL' },
        { command: 'CERTREQ', description: 'Request certificate from a certification authority.', example: 'CERTREQ' },
        { command: 'CERTUTIL', description: 'Manage certification authority (CA) files and services.', example: 'CERTUTIL' },
        { command: 'CD', description: 'Change Directory - move to a specific Folder.', example: 'CD directory_name' },
        { command: 'CHANGE', description: 'Change Terminal Server Session properties.', example: 'CHANGE' },
        { command: 'CHANGEPK', description: 'Upgrade device Edition/Product Key.', example: 'CHANGEPK' },
        { command: 'CHCP', description: 'Change the active console Code Page.', example: 'CHCP' },
        { command: 'CHDIR', description: 'Change Directory - move to a specific Folder.', example: 'CHDIR directory_name' },
        { command: 'CHKDSK', description: 'Check Disk - check and repair disk problems.', example: 'CHKDSK' },
        { command: 'CHKNTFS', description: 'Check the NTFS file system.', example: 'CHKNTFS' },
        { command: 'CHOICE', description: 'Accept keyboard input to a batch file.', example: 'CHOICE' },
        { command: 'CIPHER', description: 'Encrypt or Decrypt files/folders, overwrite data.', example: 'CIPHER' },
        { command: 'CleanMgr', description: 'Automated cleanup of Temp files, recycle bin.', example: 'CleanMgr' },
        { command: 'CLIP', description: 'Copy STDIN to the Windows clipboard.', example: 'CLIP' },
        { command: 'CLS', description: 'Clear the screen.', example: 'CLS' },
        { command: 'CMD', description: 'Start a new CMD shell.', example: 'CMD' },
        { command: 'CMDKEY', description: 'Manage stored usernames/passwords.', example: 'CMDKEY' },
        { command: 'COLOR', description: 'Change colors of the CMD window.', example: 'COLOR' },
        { command: 'COMP', description: 'Compare the contents of two files or sets of files.', example: 'COMP' },
        { command: 'COMPACT', description: 'Compress files or folders on an NTFS partition.', example: 'COMPACT' },
        { command: 'COMPRESS', description: 'Compress one or more files.', example: 'COMPRESS' },
        { command: 'CON', description: 'Console input.', example: 'CON' },
        { command: 'CONVERT', description: 'Convert a FAT drive to NTFS.', example: 'CONVERT' },
        { command: 'COPY', description: 'Copy one or more files to another location.', example: 'COPY source destination' },
        { command: 'Coreinfo', description: 'Show the mapping between logical & physical processors.', example: 'Coreinfo' },
        { command: 'CSCcmd', description: 'Client-side caching (Offline Files).', example: 'CSCcmd' },
        { command: 'CSVDE', description: 'Import or Export Active Directory data.', example: 'CSVDE' },
        { command: 'CURL', description: 'Transfer data from or to a server.', example: 'CURL' },
        { command: 'DATE', description: 'Display or set the date.', example: 'DATE' },
        { command: 'DEFRAG', description: 'Defragment hard drive.', example: 'DEFRAG' },
        { command: 'DEL', description: 'Delete one or more files.', example: 'DEL filename' },
        { command: 'DELPROF', description: 'Delete user profiles.', example: 'DELPROF' },
        { command: 'DELTREE', description: 'Delete a folder and all subfolders.', example: 'DELTREE' },
        { command: 'DevCon', description: 'Device Manager Command Line Utility.', example: 'DevCon' },
        { command: 'DIR', description: 'Display a list of files and folders.', example: 'DIR' },
        { command: 'DIRQUOTA', description: 'File Server Resource Manager Disk quotas.', example: 'DIRQUOTA' },
        { command: 'DIRUSE', description: 'Display directory sizes/usage.', example: 'DIRUSE' },
        { command: 'DISKPART', description: 'Disk Administration.', example: 'DISKPART' },
        { command: 'DISKSHADOW', description: 'Volume Shadow Copy Service.', example: 'DISKSHADOW' },
        { command: 'DISKUSE', description: 'Show the space used in folders.', example: 'DISKUSE' },
        { command: 'DISM', description: 'Deployment Image Servicing and Management.', example: 'DISM' },
        { command: 'DisplaySwitch', description: 'Specify which display to use and how to use it.', example: 'DisplaySwitch' },
        { command: 'DNSCMD', description: 'Manage DNS servers.', example: 'DNSCMD' },
        { command: 'DOSKEY', description: 'Edit command line, recall commands, and create macros.', example: 'DOSKEY' },
        { command: 'DriverQuery', description: 'Display installed device drivers.', example: 'DriverQuery' },
        { command: 'DSACLs', description: 'Active Directory ACLs.', example: 'DSACLs' },
        { command: 'DSAdd', description: 'Add items to Active Directory (user group computer).', example: 'DSAdd' },
        { command: 'DSGet', description: 'View items in Active Directory (user group computer).', example: 'DSGet' },
        { command: 'DSQuery', description: 'Search Active Directory (user group computer).', example: 'DSQuery' },
        { command: 'DSMod', description: 'Modify items in Active Directory (user group computer).', example: 'DSMod' },
        { command: 'DSMove', description: 'Move an Active Directory Object.', example: 'DSMove' },
        { command: 'DSRM', description: 'Remove items from Active Directory.', example: 'DSRM' },
        { command: 'DSREGCMD', description: 'Directory Service Registration.', example: 'DSREGCMD' },
        { command: 'DU', description: 'Display directory sizes/usage.', example: 'DU' },
        { command: 'ECHO', description: 'Display message on screen.', example: 'ECHO "Hello, World!"' },
        { command: 'ENDLOCAL', description: 'End localisation of the environment in a batch file.', example: 'ENDLOCAL' },
        { command: 'ERASE', description: 'Delete one or more files.', example: 'ERASE filename' },
        { command: 'EVENTCREATE', description: 'Add a message to the Windows event log.', example: 'EVENTCREATE' },
        { command: 'EXIT', description: 'Quit the current script/routine and set an errorlevel.', example: 'EXIT' },
        { command: 'EXPAND', description: 'Uncompress CAB files.', example: 'EXPAND' },
        { command: 'EXPLORER', description: 'Open Windows Explorer.', example: 'EXPLORER' },
        { command: 'EXTRACT', description: 'Uncompress CAB files.', example: 'EXTRACT' },
        { command: 'FC', description: 'Compare two files.', example: 'FC' },
        { command: 'FIND', description: 'Search for a text string in a file.', example: 'FIND' },
        { command: 'FINDSTR', description: 'Search for strings in files.', example: 'FINDSTR' },
        { command: 'FLTMC', description: 'Manage MiniFilter drivers.', example: 'FLTMC' },
        { command: 'FONDUE', description: 'Features on Demand User Experience Tool.', example: 'FONDUE' },
        { command: 'FOR /F', description: 'Loop command: against a set of files.', example: 'FOR /F' },
        { command: 'FOR /F', description: 'Loop command: against the results of another command.', example: 'FOR /F' },
        { command: 'FOR', description: 'Loop command: all options Files, Directory, List.', example: 'FOR' },
        { command: 'FORFILES', description: 'Batch process multiple files.', example: 'FORFILES' },
        { command: 'FORMAT', description: 'Format a disk.', example: 'FORMAT' },
        { command: 'FREEDISK', description: 'Check free disk space.', example: 'FREEDISK' },
        { command: 'FSUTIL', description: 'File and Volume utilities.', example: 'FSUTIL' },
        { command: 'FTP', description: 'File Transfer Protocol.', example: 'FTP' },
        { command: 'FTYPE', description: 'File extension file type associations.', example: 'FTYPE' },
        { command: 'GETMAC', description: 'Display the Media Access Control (MAC) address.', example: 'GETMAC' },
        { command: 'GOTO', description: 'Direct a batch program to jump to a labelled line.', example: 'GOTO' },
        { command: 'GPRESULT', description: 'Display Resultant Set of Policy information.', example: 'GPRESULT' },
        { command: 'GPUPDATE', description: 'Update Group Policy settings.', example: 'GPUPDATE' },
        { command: 'HELP', description: 'Online Help.', example: 'HELP' },
        { command: 'HOSTNAME', description: 'Display the host name of the computer.', example: 'HOSTNAME' },
        { command: 'iCACLS', description: 'Change file and folder permissions.', example: 'iCACLS' },
        { command: 'IEXPRESS', description: 'Create a self extracting ZIP file archive.', example: 'IEXPRESS' },
        { command: 'IF', description: 'Conditionally perform a command.', example: 'IF' },
        { command: 'IFMEMBER', description: 'Is the current user a member of a group.', example: 'IFMEMBER' },
        { command: 'IPCONFIG', description: 'Configure IP.', example: 'IPCONFIG' },
        { command: 'INUSE', description: 'Replace files that are in use by the OS.', example: 'INUSE' },
        { command: 'KLIST', description: 'List cached Kerberos tickets.', example: 'KLIST' },
        { command: 'MKLINK', description: 'Create a symbolic link to a directory or a file.', example: 'MKLINK link_name target' },
        { command: 'MODE', description: 'Configure a system device.', example: 'MODE' },
        { command: 'MORE', description: 'Display output, one screen at a time.', example: 'MORE' },
        { command: 'MOVE', description: 'Move files from one folder to another.', example: 'MOVE source destination' },
        { command: 'MOVEUSER', description: 'Move a user from one domain to another domain.', example: 'MOVEUSER' },
        { command: 'MSG', description: 'Send a message to a user.', example: 'MSG' },
        { command: 'MSIEXEC', description: 'Microsoft Windows Installer.', example: 'MSIEXEC' },
        { command: 'MSINFO32', description: 'Microsoft System Information.', example: 'MSINFO32' },
        { command: 'MSTSC', description: 'Open Remote Desktop Connection.', example: 'MSTSC' },
        { command: 'MV', description: 'Move files from one folder to another.', example: 'MV source destination' },
        { command: 'NET', description: 'Manage network resources.', example: 'NET' },
        { command: 'NETDOM', description: 'Domain Manager.', example: 'NETDOM' },
        { command: 'NETSH', description: 'Configure network interfaces.', example: 'NETSH' },
        { command: 'NETSTAT', description: 'Display networking statistics.', example: 'NETSTAT' },
        { command: 'NBTSTAT', description: 'NetBIOS over TCP/IP statistics.', example: 'NBTSTAT' },
        { command: 'NSLOOKUP', description: 'Query the DNS for information.', example: 'NSLOOKUP' },
        { command: 'OPENFILES', description: 'Query or disconnect open files or folders on a system.', example: 'OPENFILES' },
        { command: 'PACKAGER', description: 'Create a package for an application.', example: 'PACKAGER' },
        { command: 'PATH', description: 'Display or set a search path for executable files.', example: 'PATH' },
        { command: 'PATHPING', description: 'Trace route plus network latency and packet loss.', example: 'PATHPING' },
        { command: 'PAUSE', description: 'Suspend processing of a batch file and display a message.', example: 'PAUSE' },
        { command: 'PERFMON', description: 'Performance Monitor.', example: 'PERFMON' },
        { command: 'PING', description: 'Test a network connection.', example: 'PING' },
        { command: 'POPD', description: 'Restore the previous value of the current directory saved by PUSHD.', example: 'POPD' },
        { command: 'PORTQRY', description: 'Display the status of ports and services.', example: 'PORTQRY' },
        { command: 'POWERCFG', description: 'Configure power settings on a system.', example: 'POWERCFG' },
        { command: 'PRINT', description: 'Print a text file.', example: 'PRINT' },
        { command: 'PROMPT', description: 'Change the command prompt.', example: 'PROMPT' },
        { command: 'PS', description: 'List processes currently running on the system.', example: 'PS' },
        { command: 'PUSHD', description: 'Save the current directory for use by the POPD command.', example: 'PUSHD' },
        { command: 'QGREP', description: 'Search files for lines that match a pattern.', example: 'QGREP' },
        { command: 'QUERY', description: 'Display information about terminal sessions, processes, and network resources.', example: 'QUERY' },
        { command: 'QUSER', description: 'Display information about users logged on to the system.', example: 'QUSER' },
        { command: 'RD', description: 'Remove an empty directory.', example: 'RD directory_name' },
        { command: 'RECOVER', description: 'Recover readable data from a bad or defective disk.', example: 'RECOVER' },
        { command: 'REG', description: 'Read, set, or delete registry keys and values.', example: 'REG' },
        { command: 'REM', description: 'Record comments (remarks) in a batch file or CONFIG.SYS.', example: 'REM' },
        { command: 'REN', description: 'Rename a file or files.', example: 'REN old_filename new_filename' },
        { command: 'RENAME', description: 'Rename a file or files.', example: 'RENAME old_filename new_filename' },
        { command: 'REPLACE', description: 'Replace files.', example: 'REPLACE' },
        { command: 'RESET', description: 'Reset the session subsystem hardware abstraction layer (HAL).', example: 'RESET' },
        { command: 'RMDIR', description: 'Remove an empty directory.', example: 'RMDIR directory_name' },
        { command: 'ROBOCOPY', description: 'Robust File and Folder Copy.', example: 'ROBOCOPY' },
        { command: 'ROUTE', description: 'Manipulate network routing tables.', example: 'ROUTE' },
        { command: 'RUNAS', description: 'Run a program as another user.', example: 'RUNAS' },
        { command: 'RUNDLL32', description: 'Run a DLL command (add/remove print connections).', example: 'RUNDLL32' },
        { command: 'SC', description: 'Service Control.', example: 'SC' },
        { command: 'SCHTASKS', description: 'Schedule a command to run at a specific time.', example: 'SCHTASKS' },
        { command: 'SCLIST', description: 'Display services.', example: 'SCLIST' },
        { command: 'SDBINST', description: 'Microsoft Compatibility Database Install.', example: 'SDBINST' },
        { command: 'SECEDIT', description: 'Configure and analyze system security by comparing your current configuration to a template.', example: 'SECEDIT' },
        { command: 'SET', description: 'Display, set, or remove session environment variables.', example: 'SET' },
        { command: 'SETLOCAL', description: 'Begin localisation of environment changes in a batch file.', example: 'SETLOCAL' },
        { command: 'SETX', description: 'Set environment variables.', example: 'SETX' },
        { command: 'SFC', description: 'System File Checker.', example: 'SFC' },
        { command: 'SHARE', description: 'List or edit a file share or print share on a computer or print server.', example: 'SHARE' },
        { command: 'SHIFT', description: 'Change the position of replaceable parameters in a batch file.', example: 'SHIFT' },
        { command: 'SHUTDOWN', description: 'Shutdown the computer.', example: 'SHUTDOWN' },
        { command: 'SLEEP', description: 'Wait for x seconds.', example: 'SLEEP' },
        { command: 'SLMGR', description: 'Software Licensing Management Tool.', example: 'SLMGR' },
        { command: 'SORT', description: 'Sort input.', example: 'SORT' },
        { command: 'START', description: 'Start a program or command in a separate window.', example: 'START' },
        { command: 'SUBST', description: 'Associate a path with a drive letter.', example: 'SUBST' },
        { command: 'SYSTEMINFO', description: 'List system configuration.', example: 'SYSTEMINFO' },
        { command: 'SYSTEMROOT', description: 'Locate the system root of the current Windows installation.', example: 'SYSTEMROOT' },
        { command: 'TAKEOWN', description: 'Take ownership of a file or folder.', example: 'TAKEOWN' },
        { command: 'TASKKILL', description: 'Terminate a running process or application.', example: 'TASKKILL' },
        { command: 'TASKLIST', description: 'List all running applications on a Windows system.', example: 'TASKLIST' },
        { command: 'TELNET', description: 'Telnet to another computer or device from the command line.', example: 'TELNET' },
        { command: 'TIME', description: 'Display or set the system time.', example: 'TIME' },
        { command: 'TITLE', description: 'Set the window title for a CMD.EXE session.', example: 'TITLE' },
        { command: 'TOUCH', description: 'Change file timestamps.', example: 'TOUCH' },
        { command: 'TRACERT', description: 'Trace the route to a remote host.', example: 'TRACERT' },
        { command: 'TREE', description: 'Graphically display the directory structure of a drive or path.', example: 'TREE' },
        { command: 'TYPE', description: 'Display the contents of a text file.', example: 'TYPE' },
        { command: 'USRSTAT', description: 'List domain usernames and last login.', example: 'USRSTAT' },
        { command: 'VER', description: 'Display the version number.', example: 'VER' },
        { command: 'VERIFY', description: 'Tell Windows whether to verify that your files are written correctly to a disk.', example: 'VERIFY' },
        { command: 'VOL', description: 'Display a disk label.', example: 'VOL' },
        { command: 'VSSADMIN', description: 'Volume Shadow Copy Service administrative command-line tool.', example: 'VSSADMIN' },
        { command: 'W32TM', description: 'Windows Time Service.', example: 'W32TM' },
        { command: 'WAITFOR', description: 'Send or wait for a signal on a system.', example: 'WAITFOR' },
        { command: 'WHERE', description: 'Search for files in a directory tree.', example: 'WHERE' },
        { command: 'WHOAMI', description: 'Output the current UserName and domain.', example: 'WHOAMI' },
        { command: 'WMIC', description: 'Windows Management Instrumentation Command-line.', example: 'WMIC' },
        { command: 'XCACLS', description: 'Change file and folder permissions.', example: 'XCACLS' },
        { command: 'XCOPY', description: 'Copy files and directories, including subdirectories.', example: 'XCOPY' },
        { command: 'XCOPY32', description: 'Copy files and directories, including subdirectories.', example: 'XCOPY32' },
        { command: 'Y', description: 'Suppress prompt to confirm overwriting a file.', example: 'Y' },
        { command: 'ZOOM', description: 'Enlarge the screen display.', example: 'ZOOM' },
    ];

    res.json(windowsCommands);
});

module.exports = router;
